[versions]

fabric-loader = "0.16.10"
fabric-language-kotlin = "1.13.0+kotlin.2.1.0"
fabric-api = "0.128.1"

kotlin = "2.1.20"
kotlin-symbol-processor = "2.1.20-2.0.0"

skyblockapi = "1.0.0-beta.140-multiversion+build.22"
hypixelapi = "1.0.1+build.1+mc1.21"

meowdding-lib = "1.0.53-multiversion+build.13"
meowdding-patches = "1.0.5"
meowdding-repo = "1.0.16"
meowdding-resources = "1.0.12"
meowdding-ktmodules = "1.0.5"
meowdding-ktcodecs = "1.0.25"

# Dev Dependencies
devauth = "1.2.1"
modmenu = "14.0.0-rc.2"

terrarium-cloche = "0.11.6"

[libraries]

fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-language-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-language-kotlin" }

skyblockapi = { module = "tech.thatgravyboat:skyblock-api", version.ref = "skyblockapi" }
hypixelapi = { module = "maven.modrinth:hypixel-mod-api", version.ref = "hypixelapi" }

resourceful-lib1215 = { module = "com.teamresourceful.resourcefullib:resourcefullib-fabric-1.21.5", version = "3.5.0" }
resourceful-lib1218 = { module = "com.teamresourceful.resourcefullib:resourcefullib-fabric-1.21.6", version = "3.6.0" }
resourceful-config1215 = { module = "com.teamresourceful.resourcefulconfig:resourcefulconfig-fabric-1.21.5", version = "3.5.14" }
resourceful-config1218 = { module = "com.teamresourceful.resourcefulconfig:resourcefulconfig-fabric-1.21.7", version = "3.7.0" }
resourceful-config-kotlin = { module = "com.teamresourceful.resourcefulconfigkt:resourcefulconfigkt-fabric-1.21.5", version = "3.5.12" }
olympus-lib1215 = { module = "earth.terrarium.olympus:olympus-fabric-1.21.5", version = "1.3.6" }
olympus-lib1218 = { module = "earth.terrarium.olympus:olympus-fabric-1.21.7", version = "1.5.2" }

meowdding-lib = { module = "me.owdding.meowdding-lib:meowdding-lib", version.ref = "meowdding-lib" }
meowdding-patches = { module = "me.owdding.patches:patches", version.ref = "meowdding-patches" }
meowdding-ktmodules = { module = "me.owdding.ktmodules:KtModules", version.ref = "meowdding-ktmodules" }
meowdding-ktcodecs = { module = "me.owdding.ktcodecs:KtCodecs", version.ref = "meowdding-ktcodecs" }

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }

devauth = { module = "me.djtheredstoner:DevAuth-fabric", version.ref = "devauth" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }

[plugins]

terrarium-cloche = { id = "earth.terrarium.cloche", version.ref = "terrarium-cloche" }
meowdding-resources = { id = "me.owdding.resources", version.ref = "meowdding-resources" }
meowdding-repo = { id = "me.owdding.repo", version.ref = "meowdding-repo" }
kotlin-symbol-processor = { id = "com.google.devtools.ksp", version.ref = "kotlin-symbol-processor" }
